version: '3.4'

services:
  cabinet.api:
    image: ${DOCKER_REGISTRY-}cabinetapi
    build:
      context: .
      dockerfile: Microservices/Cabinet/Cabinet.API/Dockerfile
    depends_on:
      - sqldata
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Rvbximzs1
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
  envoygateway:
    image: envoyproxy/envoy-dev
    volumes:
      - ./Gateways/Envoy/:/etc/envoy
    ports:
    - "10000:10000"
    - "9901:9901"
